var phrases = [
	'You have not idea what are doing, right?',
	'Excellent, you are fired 😒',
	'Ufff, you need work hard...',
	'Really? You sucks...',
	'Came on! Is not to hard!',
	'Well.... hm......',
	'Why im doing this!',
	'Please, go and study again..',
	'🥩🍊🍐🍌...😒',
	'...Close enough, meh..',
	'You win a 🍌!',
	'Well... you can do it better, you know?',
	'Awesome! Naa, i am joking, you socks...',
	'...emm.. ok (?)',
	'To the biggest I called Cuca',
	'Try again.. please... PLEASE!!',
	'...hm...😒',
	'Well, not bad, but is insufficient, slave!',
	'Come on! Do a better job!',
	'Well, is ok... only ok.',
	'Holy guacamole!',
	'You do not miss that!!! hahaha... try again, realy, do it 😒',
	"Muuuahahaha, you can't do it!",
	'You must to answer only 3 cards to win! Looser...😒',
	'Good record! But is not the best 😑',
	'Was easy right? muejeje...😍'
];
